CREATE TABLE IF NOT EXISTS vlans (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    vlan_id INT NOT NULL,
    name VARCHAR(255) NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
